### ISSUE TITLE
Fail to build [1.1.9.2] [Player Animator 1.3] [MC Creator 2022.3]

### ISSUE THREAD

**Issue by BiggiestBoy** [NerdyPuzzle/MCreator-Player-Animator#1]
I'm trying to start my mod and it comes up with these build errors

I made sure I had the name set to "SetupAnimations" a thousand times and it wont fix this

Executing Gradle task: runClient 
Build info: MCreator 2022.3.47418, forge-1.19.2, 64-bit, 32683 MB, Windows 11, JVM 17.0.3, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2022-11-21-20:35:43 
  
> Configure project : 
The code of this workspace uses official obfuscation mappings provided by Mojang. These mappings fall under their associated license you should be fully aware of. 
(c) 2020 Microsoft Corporation. These mappings are provided "as-is" and you bear the risk of using them. You may copy and use the mappings for development purposes, 
but you may not redistribute the mappings complete and unmodified. Microsoft makes no warranties, express or implied, with respect to the mappings provided here. 
Use and modification of this document or the source code (in any form) of Minecraft: Java Edition is governed by the Minecraft End User License Agreement available 
at https://account.mojang.com/documents/minecraft_eula. 
  
> Task :compileJava FAILED 
[C:\Users\jkirc\MCreatorWorkspaces\quirk\src\main\java\net\mcreator\quirk\procedures\SetupAnimationsProcedure.java:17](file:///C:/Users/jkirc/MCreatorWorkspaces/quirk/src/main/java/net/mcreator/quirk/procedures/SetupAnimationsProcedure.java:17): error: cannot find symbol 
   public static final Map<AbstractClientPlayer, ModifierLayer<IAnimation>> animationData = new IdentityHashMap<>(); 
                                                 ^ 
  symbol:   class ModifierLayer 
  location: class SetupAnimationsProcedure 
[C:\Users\jkirc\MCreatorWorkspaces\quirk\src\main\java\net\mcreator\quirk\procedures\SetupAnimationsProcedure.java:17](file:///C:/Users/jkirc/MCreatorWorkspaces/quirk/src/main/java/net/mcreator/quirk/procedures/SetupAnimationsProcedure.java:17): error: cannot find symbol 
   public static final Map<AbstractClientPlayer, ModifierLayer<IAnimation>> animationData = new IdentityHashMap<>(); 
                                                               ^ 
  symbol:   class IAnimation 
  location: class SetupAnimationsProcedure 
[C:\Users\jkirc\MCreatorWorkspaces\quirk\src\main\java\net\mcreator\quirk\procedures\SetupAnimationsProcedure.java:24](file:///C:/Users/jkirc/MCreatorWorkspaces/quirk/src/main/java/net/mcreator/quirk/procedures/SetupAnimationsProcedure.java:24): error: cannot find symbol 
   private static void registerPlayerAnimation(AbstractClientPlayer player, AnimationStack stack) { 
                                                                            ^ 
  symbol:   class AnimationStack 
  location: class SetupAnimationsProcedure 
[C:\Users\jkirc\MCreatorWorkspaces\quirk\src\main\java\net\mcreator\quirk\procedures\Ability1Procedure.java:39](file:///C:/Users/jkirc/MCreatorWorkspaces/quirk/src/main/java/net/mcreator/quirk/procedures/Ability1Procedure.java:39): error: cannot find symbol 
               animation.setAnimation(new KeyframeAnimationPlayer(PlayerAnimationRegistry.getAnimation(new ResourceLocation("quirk", "punch")))); 
                                          ^ 
  symbol:   class KeyframeAnimationPlayer 
  location: class Ability1Procedure 
[C:\Users\jkirc\MCreatorWorkspaces\quirk\src\main\java\net\mcreator\quirk\procedures\Ability1Procedure.java:39](file:///C:/Users/jkirc/MCreatorWorkspaces/quirk/src/main/java/net/mcreator/quirk/procedures/Ability1Procedure.java:39): error: cannot find symbol 
               animation.setAnimation(new KeyframeAnimationPlayer(PlayerAnimationRegistry.getAnimation(new ResourceLocation("quirk", "punch")))); 
                                                                  ^ 
  symbol:   variable PlayerAnimationRegistry 
  location: class Ability1Procedure 
[C:\Users\jkirc\MCreatorWorkspaces\quirk\src\main\java\net\mcreator\quirk\procedures\SetupAnimationsProcedure.java:21](file:///C:/Users/jkirc/MCreatorWorkspaces/quirk/src/main/java/net/mcreator/quirk/procedures/SetupAnimationsProcedure.java:21): error: package PlayerAnimationAccess does not exist 
      PlayerAnimationAccess.REGISTER_ANIMATION_EVENT.register(SetupAnimationsProcedure::registerPlayerAnimation); 
                           ^ 
[C:\Users\jkirc\MCreatorWorkspaces\quirk\src\main\java\net\mcreator\quirk\procedures\SetupAnimationsProcedure.java:25](file:///C:/Users/jkirc/MCreatorWorkspaces/quirk/src/main/java/net/mcreator/quirk/procedures/SetupAnimationsProcedure.java:25): error: cannot find symbol 
      var layer = new ModifierLayer<>(); 
                      ^ 
  symbol:   class ModifierLayer 
  location: class SetupAnimationsProcedure 
7 errors 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --stacktrace option to get the stack trace. 
> Run with --info or --debug option to get more log output. 
> Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 2s 
1 actionable task: 1 executed 
  
BUILD FAILED 
Task completed in 4 seconds

Let me know if you need more info

**Comment by BiggiestBoy** [comment]
I use MC Creator 2022.3

**Comment by NerdyPuzzle** [comment]
And you also forgot the fact that this is an external API a thousand times, meaning you need to enable it in workspace settings for it to do anything.
