### ISSUE TITLE
Sorry for keep on asking for this error.

### ISSUE THREAD

**Issue by MetalMr** [NerdyPuzzle/MCreator-Player-Animator#10]
Please help I need a list of instructions or a very detailed guide on how to fix this problem because I can't go on Minecraft and do stuff all I can do is look at an error page or just look at the mod folder so can you ask me a list of questions instead of putting this on invalid. Also I have been working on this project for 2 years and I have not finished it because of this error and I think I know the reason why I am getting this error because I'm missing the Player Animator Library but I don't know how to use it to make my mod work.

**Comment by NerdyPuzzle** [comment]
Provide an example workspace where you reproduce the thing.

**Comment by MetalMr** [comment]
When you say thing do you mean the mod

**Comment by MetalMr** [comment]
or like show you what I'm doing to make the mod

**Comment by MetalMr** [comment]
Do i send it or take a picture. If i do have to send it how?

**Comment by MetalMr** [comment]
![image](https://user-images.githubusercontent.com/123501142/214998723-d83fcd99-b1e8-433d-a27f-1875a0d2521c.png)

**Comment by NerdyPuzzle** [comment]
the workspace. send the workspace.

**Comment by NerdyPuzzle** [comment]
the zip it.

**Comment by MetalMr** [comment]
[Test for Test.zip](https://github.com/NerdyPuzzle/MCreator-Player-Animator/files/10524250/Test.for.Test.zip)

**Comment by MetalMr** [comment]
I sent it

**Comment by MetalMr** [comment]
[Test.for.Test (1).zip](https://github.com/NerdyPuzzle/MCreator-Player-Animator/files/10528407/Test.for.Test.1.zip)

**Comment by MetalMr** [comment]
did you get the file?
