### ISSUE TITLE
animationData error

### ISSUE THREAD

**Issue by deadoo432kik** [NerdyPuzzle/MCreator-Player-Animator#17]
Executing Gradle task: runClient 
Build info: MCreator 2023.1.10610, forge-1.19.2, 64-bit, 7502 MB, Windows 11, JVM 17.0.5, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2023-05-09-21:33:37 
  
> Configure project : 
The code of this workspace uses official obfuscation mappings provided by Mojang. These mappings fall under their associated license you should be fully aware of. 
(c) 2020 Microsoft Corporation. These mappings are provided "as-is" and you bear the risk of using them. You may copy and use the mappings for development purposes, 
but you may not redistribute the mappings complete and unmodified. Microsoft makes no warranties, express or implied, with respect to the mappings provided here. 
Use and modification of this document or the source code (in any form) of Minecraft: Java Edition is governed by the Minecraft End User License Agreement available 
at https://account.mojang.com/documents/minecraft_eula. 
  
> Task :compileJava FAILED 
[C:\Users\boray\MCreatorWorkspaces\utily_animation\src\main\java\net\mcreator\utilyanimation\procedures\SetupAnimationsProcedure.java:38](file:///C:/Users/boray/MCreatorWorkspaces/utily_animation/src/main/java/net/mcreator/utilyanimation/procedures/SetupAnimationsProcedure.java:38): error: cannot find symbol 
            var animation = SetupAnimationsProcedure.animationData.get((Player) entity); 
                                                    ^ 
  symbol:   variable animationData 
  location: class SetupAnimationsProcedure 
1 error 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --stacktrace option to get the stack trace. 
> Run with --info or --debug option to get more log output. 
> Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 2s 
1 actionable task: 1 executed 
  
BUILD FAILED 
Task completed in 3 seconds

**Comment by deadoo432kik** [comment]
really need help I try everything but nothing helps the problem

**Comment by NerdyPuzzle** [comment]
using outdated version
