### ISSUE TITLE
Game crashes once loading reaches 100%. Help required ASAP.

### ISSUE THREAD

**Issue by TiberianEuan** [NerdyPuzzle/MCreator-Player-Animator#18]
[crash-2023-06-02_18.05.45-client.txt](https://github.com/NerdyPuzzle/MCreator-Player-Animator/files/11633353/crash-2023-06-02_18.05.45-client.txt)
[issue problem.zip](https://github.com/NerdyPuzzle/MCreator-Player-Animator/files/11633354/issue.problem.zip)

Above is the crash file and the workspace sharable zip.

**Comment by NerdyPuzzle** [comment]
All I can suggest is splitting the animations into individual files, as it seems to not be able to read the file properly. Then you'll see which one causes it.

**Comment by TiberianEuan** [comment]
the files are already seperate.
