### ISSUE TITLE
Resetting animations

### ISSUE THREAD

**Issue by fridays1881** [NerdyPuzzle/MCreator-Player-Animator#19]
When I use an animation theres times the animation gets locked and wont change back to another thing (on active potion effect tick do "float" animation, when the effect wears off the animation will stay) Is there anyway to reset the animations back to normal?

**Comment by NerdyPuzzle** [comment]
that's just client-side desync with potion effects

**Comment by fridays1881** [comment]
> that's just client-side desync with potion effects

Is there anyway to make it work with ontick things though?
