### ISSUE TITLE
Game Crashes whenever using an animation [1.1.9.2] [Player Animator 1.3] [MC Creator 2022.3]

### ISSUE THREAD

**Issue by BiggiestBoy** [NerdyPuzzle/MCreator-Player-Animator#2]
I'm sorry to leave another ticket here, I'm new to modding and can't figure this out for my mod

I used blockbench geckolib plugin for animating and I'd exporting the json without renaming it.

Heres is the animation: 
[model.animation.airforce.txt](https://github.com/NerdyPuzzle/MCreator-Player-Animator/files/10071932/model.animation.airforce.txt)
^This is a .json on my pc

Whenever I try to play the animation the game spits out this crash

[crash-2022-11-22_17.36.23-client.txt](https://github.com/NerdyPuzzle/MCreator-Player-Animator/files/10071917/crash-2022-11-22_17.36.23-client.txt)

I can provide any more information if you'd like, sorry again.

**Comment by NerdyPuzzle** [comment]
That is not a geckolib animation.

**Comment by BiggiestBoy** [comment]
how is it not a geckolib animation?

**Comment by NerdyPuzzle** [comment]
You put it in .txt format so I assumed it wasn't. The name you use in the procedure should be the full name of the file except the .json part

**Comment by BiggiestBoy** [comment]
it is I think
![image](https://user-images.githubusercontent.com/41413575/203581606-fdffca1e-2101-4f11-98a0-cdc113b06fae.png)
Sorry again for bothering you

**Comment by BiggiestBoy** [comment]
Is there anything I can do to fix this
