### ISSUE TITLE
Animations not working in multiplayer server

### ISSUE THREAD

**Issue by GreenShinyRock** [NerdyPuzzle/MCreator-Player-Animator#21]
Hello. Recently my friend has been trying to make animations for his multiplayer server, but whenever he tries to do so it always seem to either fail or completely break. I don't know if you guys are aware of this or have it been already reported, but I just wanted to let you know.

**Comment by StickWizard** [comment]
same issue

**Comment by MichaelJackson23** [comment]
I think this is a duplicate issue but animations don't work in multiplayer for me either

**Comment by NerdyPuzzle** [comment]
they do now
