### ISSUE TITLE
crash when loading a world

### ISSUE THREAD

**Issue by elyesishere** [NerdyPuzzle/MCreator-Player-Animator#23]
so i followed every step for the animation to work (made in blockbench) and when i put the animation in a new procedure (not the SetupAnimations) the animation doesn't work because i didn't change the trigger event. but when i put the trigger event to "on player tick update", the game crashes when loading the world, what should i do?

**Comment by Gamer553514** [comment]
You have to go in to the prozedur and change the name for example: animation.model.animationname 
Hope that helped

**Comment by Kisilisizkisi** [comment]
I didn't understand how to do this so I just changed the name of the procedure but it didn't work, can you explain a little more?
