### ISSUE TITLE
Plugin completely breaks in 2023.3

### ISSUE THREAD

**Issue by pploh** [NerdyPuzzle/MCreator-Player-Animator#25]
So I had updated my workspace from 2023.2 to 2023.3 and thinking that the code wouldn't have changed that much and how most plugins I have still worked, I assumed the same for this one. But the PlayerAnimator plugin just won't work, at all. And I'm assuming it is because of the MCreator version. So when you get the chance(I'm pretty sure you mentioned you serve in the military) would you be able to do a quick port to 2023.3? There are no logs or errors for me to show since they do not pop up on the console.

**Comment by NerdyPuzzle** [comment]
Haven't ported it yet. I'll do it next time I have days off.

**Comment by pploh** [comment]
Nevermind, it was apparently because the SetUpAnimations didn't work since I had changed my mod ID, changing it made the plugin work again.(Closing this issue)
