### ISSUE TITLE
Doesn't include bendy-lib

### ISSUE THREAD

**Issue by Lightning-Driver** [NerdyPuzzle/MCreator-Player-Animator#29]
Hi there. 

If you haven't heard of bendy-lib, it is made by the same person as the one who made player animator, only with one key difference, and that is that it adds to the player elbows, knees, and joints. The problem is that with your plugin, player animator seems already to be installed without me having to install it from the beginning. However, it is annoying because of the fact that I can't use bendy-lib, since the game crashes when it sees both player-animator and bendy-lib together for some reason. My guess is that bendy-lib already has player-animator in it.

**Comment by NerdyPuzzle** [comment]
No clue, but I'm not going to be adding support for it as documentation is lacking and I have no clue how it works.

**Comment by Lightning-Driver** [comment]
Alright no problem

**Comment by Lightning-Driver** [comment]
Sorry to talk about this again, but I think to add bendy-lib would really help your plugin, and it's very simple to add. If you look at this link [https://github.com/KosmX/minecraftPlayerAnimator](url), in the README.md, under "Include in your dev environment", then under "ForgeGradle," you'll find a comment that says 

//Bendy-lib also has a Forge version:
//runtimeOnly fg.deobf("io.github.kosmx.bendy-lib:bendy-lib-forge:${project.bendylib_version}")

Adding this should add bendy-lib, which, as I said previously, adds more joints such as elbows and knees. 
I'm just trying to be helpful and suggest a way to improve your plugin, and I totally understand if you decide not to add this at all. 
Thank you for reading this.
