### ISSUE TITLE
Game crashing whenever animation played [1.1.9.2] [Player Animator 1.3] [MC Creator 2022.3]

### ISSUE THREAD

**Issue by BiggiestBoy** [NerdyPuzzle/MCreator-Player-Animator#3]
Sorry to bother

I still can't manage to get my animation to play

I believe I have everything set up

It crashes whenever I click the keybind I set the procedure to

![image](https://user-images.githubusercontent.com/41413575/204072193-81600105-0352-4087-a9c0-4e817e12e922.png)

![image](https://user-images.githubusercontent.com/41413575/204072209-bc84bce3-8895-465d-bb05-4e7d540a3053.png)

![image](https://user-images.githubusercontent.com/41413575/204072223-3d7613cf-0203-4a7a-b101-96b76cdc296e.png)

Here's my crash file

[crash-2022-11-22_17.36.23-client.txt](https://github.com/NerdyPuzzle/MCreator-Player-Animator/files/10095665/crash-2022-11-22_17.36.23-client.txt)

I'm sorry if I keep bothering you, I've just been working on trying to fix this for a while. Any help is appreciated

**Comment by NerdyPuzzle** [comment]
Not a plugin issue. I suggest naming the animation a single word without dots when creating it in blockbench.

**Comment by BiggiestBoy** [comment]
That fixed it, I had to change the name in the file itself too, thank you so much!
