### ISSUE TITLE
Support 1.16.5

### ISSUE THREAD

**Issue by Lightning-Driver** [NerdyPuzzle/MCreator-Player-Animator#30]
Sorry to bother you, but I was wondering if you could add support to 1.16.5? I searched online and found that Player Animator is forge 1.16+, meaning it should be able to support 1.16.5. Is there a specific reason why it doesn't support it? 
Again, sorry if I'm bother you.

**Comment by NerdyPuzzle** [comment]
Because I chose not to

**Comment by Lightning-Driver** [comment]
Well, I looked through your plugin and found that the code for the procedures is the same for the different versions of forge, so do you think 1.16.5 would also have the same code? I'm just asking so I could try it out myself.
Thank you for your time. Sorry to bother you again. I think I'm getting a bit annoying, since I know you're a busy person with lots of very useful mods :/

**Comment by NerdyPuzzle** [comment]
No clue, since I didn't check.
