### ISSUE TITLE
Plugin breaks client-side procedures

### ISSUE THREAD

**Issue by SaltyWater-Mods** [NerdyPuzzle/MCreator-Player-Animator#33]
- Plugin is breaking client side procedures like 'delta movement'.

**Comment by NerdyPuzzle** [comment]
In what way is it breaking them? There is nothing in the plugin that would do that...

**Comment by SaltyWater-Mods** [comment]
![This is the code (1)](https://github.com/user-attachments/assets/0c31d4e7-a1a4-4c8f-80ae-23bc47bcc188)

**Comment by SaltyWater-Mods** [comment]
https://github.com/user-attachments/assets/446c2670-1fcd-4997-b5de-e95127b223f4

**Comment by SaltyWater-Mods** [comment]
In the video, resetting poses with sneaking only worked the first time exactly because of the problem I'm having, If I walk, It will ignore every variable and NBT tag set and only trigger the animation block, meaning I was walking normally while the game still thinking I had the variable of sitting set to true.
I think, this happens due to the delta movement block being client side, and the 1.9 version of the plugin triggering animations server side. It must be conflicting somehow. As in the last plugin version 1.8.1 everything worked fine.

**Comment by NerdyPuzzle** [comment]
If you want it to only trigger on the client then do if clientside before triggering the animation. The procedure block still has the code that runs on the client.

**Comment by SaltyWater-Mods** [comment]
Does this make the animation trigger in server-side?

**Comment by NerdyPuzzle** [comment]
No

**Comment by SaltyWater-Mods** [comment]
And If I want to make it trigger server side?

**Comment by NerdyPuzzle** [comment]
Then you figure out how to make your procedure work on the server

**Comment by SaltyWater-Mods** [comment]
I understand, but the thing is, this procedure worked fine in version 1.8.1, even if didn't trigger server-side. Now it doesn't work properly with or without triggering it only on client side. It isn't a Mcreator bug, I tested it in 2024.1 both versions 1.9 and 1.8.1 too, and only with the 1.9 version of the plugin I get this strange behavior in those client-side blocks.

**Comment by NerdyPuzzle** [comment]
That is the fault of your procedure, not the plugin. Trying to use clientside blocks on the server will result in unpredictable behaviour.

**Comment by SaltyWater-Mods** [comment]
Oh, that does makes a lot of sense. Thank you very much!
