### ISSUE TITLE
SetupAnimations is bracketed as wrong

### ISSUE THREAD

**Issue by Thalasian** [NerdyPuzzle/MCreator-Player-Animator#38]
![image_2024-11-26_202602217](https://github.com/user-attachments/assets/b3554e02-c9f7-4848-88fb-b8a57bef95e5)
![image](https://github.com/user-attachments/assets/c008b8b6-5bee-4b5e-95be-58216b20ee12)

**Comment by NerdyPuzzle** [comment]
Enable the player animator API
