### ISSUE TITLE
Game crashes whenever animation is played [1.18.2] 

### ISSUE THREAD

**Issue by Dolphos** [NerdyPuzzle/MCreator-Player-Animator#4]
So, I followed the instructions on the mcreator plugin website step-by-step and checked that the player_animations folder is in the right place. etc. 
i made multiple animations with blockbench and pasted them into the right folder. and as said, did the rest of the tutorial, but when i try and execute the animation, which is called by a keybind, the game just crashes.
The Mcreator console log is attached.
[crsh-log_Mcreator26.11.2022.txt](https://github.com/NerdyPuzzle/MCreator-Player-Animator/files/10097127/crsh-log_Mcreator26.11.2022.txt)

**Comment by NerdyPuzzle** [comment]
java.lang.IllegalArgumentException: Animation can not be null 
Not a plugin issue, an issue with your animation name. I suggest you name your animations a single word before exporting them.

**Comment by Dolphos** [comment]
I tried saving the .json animation file with a single word name and it still doesnt seem to work.

**Comment by NerdyPuzzle** [comment]
the name inside the animation file for the animation must match the file name.

**Comment by Dolphos** [comment]
thank you very much. i finally got it to work. :)
Great plugin and excellent help. thanks!
