### ISSUE TITLE
Animations wont play for other players in a server [1.1.9.2] [Player Animator 1.3] [MC Creator 2022.3]

### ISSUE THREAD

**Issue by MichaelJackson23** [NerdyPuzzle/MCreator-Player-Animator#6]
My friends and I were testing the mod and none of the animations would play for them but would play for the user

Here are examples

My pov:
![Untitled video - Made with Clipchamp (1)](https://user-images.githubusercontent.com/41413575/205422901-ecfc855f-dbea-40dc-8d99-24defb6d8f68.gif)

His pov:
![Untitled video - Made with Clipchamp](https://user-images.githubusercontent.com/41413575/205422917-e1be23b3-fbc7-4f41-8c08-d1a0b526931d.gif)

You can also recreate this issue by using this procedure 
![image](https://user-images.githubusercontent.com/41413575/205423043-5f909e5e-8682-4193-b70f-28aaa88b4ee3.png)

**Comment by BiggiestBoy** [comment]
I used "player-animation-lib-forge-0.4.0" for this ticket but when you go back to "player-animation-lib-forge-0.3.5" and use animation in game it'll spit out this crash as well

[crash-2022-12-04_00.49.29-client.txt](https://github.com/NerdyPuzzle/MCreator-Player-Animator/files/10191360/crash-2022-12-04_00.49.29-client.txt)

**Comment by NerdyPuzzle** [comment]
The latest version of the library should always be used. I'm aware of this issue and am still searching for a solution.

**Comment by BiggiestBoy** [comment]
I believe in you!

**Comment by MichaelJackson23** [comment]
Are there any updates to this?

**Comment by MichaelJackson23** [comment]
any updates?

**Comment by NerdyPuzzle** [comment]
If I can manage to solve this it will be in the next update.

**Comment by MichaelJackson23** [comment]
Anything new?

**Comment by MichaelJackson23** [comment]
Hey man, any progress?

**Comment by MichaelJackson23** [comment]
I noticed the plugin was updated, was this issue solved?

**Comment by MichaelJackson23** [comment]
I just tested it in multiplayer, it wasn't fixed

**Comment by StickWizard** [comment]
same issue

**Comment by NerdyPuzzle** [comment]
they do now
