### ISSUE TITLE
Mcreator build problem in 1.18.2

### ISSUE THREAD

**Issue by Dolphos** [NerdyPuzzle/MCreator-Player-Animator#7]
Hello again, so I've been getting some crashes of the MInecraft client, when loading with animations in the player_animation folder.
Everything is working perfectly until I add the new animations I've made for the Player. I checked everything concerning the names of the animations etc. and them being the same in the .json file...
But when I try and run the client via Mcreator, it keeps crashing.
Here is my log:
[Dolphos Mcreator Crash log 22_01_2023.txt](https://github.com/NerdyPuzzle/MCreator-Player-Animator/files/10474558/Dolphos.Mcreator.Crash.log.22_01_2023.txt)

Hope, you can help me once again.
Greetings, Dolphos. :)

**Comment by NerdyPuzzle** [comment]
Either you used an unsupported (by player animator) easing, or you didn't use the geckolib animation utils blockbench plugin to make the animations, I cannot know which. The crash points to something being wrong with the file.

**Comment by Dolphos** [comment]
OK, thank you. I'll look into those two things.
Thanks for the quick response. 
Have a nice day :)

**Comment by Dolphos** [comment]
It seemed, to have been an issue with the easing, as the kind of easing from Blockbench I was using, wasn't supported by the plugin. 
Now it is working pefectly fine.
Issue resolved.
