### ISSUE TITLE
Java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by MetalMr** [NerdyPuzzle/MCreator-Player-Animator#8]
I don't know if I'm doing anything wrong but I am stuck, I keep on getting this error no matter how I try and fix it

**Comment by NerdyPuzzle** [comment]
Where do you get that error? please explain.

**Comment by MetalMr** [comment]
When i am opening minecraft

**Comment by MetalMr** [comment]
I am making a Metal gear Rising game (So Don't Laugh.) 

![poos](https://user-images.githubusercontent.com/123501142/214444319-fe9b8266-e288-41f0-90d8-08de91d1b15a.png)

**Comment by MetalMr** [comment]
Also I don't know if im doing anything wrong (I have not checked the comment section of the mcreator page)

**Comment by NerdyPuzzle** [comment]
You need to install the player animator library mod

**Comment by MetalMr** [comment]
How though (I am new to coding)

**Comment by MetalMr** [comment]
Do I put into the mod file in minecraft
