### ISSUE TITLE
Help! I have installed the PlayerAnimatorLibrary but still NoClassDefFoundError Also I am making a Metal Gear Rising Mod so don't Laugh.

### ISSUE THREAD

**Issue by MetalMr** [NerdyPuzzle/MCreator-Player-Animator#9]
I have put the PlayerAnimatorLIbrary mod into the Minecraft mod folder then got a 1.19.2 forge (Mcreator 2022.3) Then I put my mod into the Mod folder (In the Mod that I made I made the animation saved it opened the file to see the code in Visual Studio Code I copy the code and made a folder in Resources (Gradle) then in assets then in MyMod then I made a .json file named it Jetstreamsamtest1.json I opened Jetstreamsamtest1.json pasted the code inside then clicked the X then the Save thing popped up then I clicked save then I made a procedure called SetupAnimations put Player Animator thing in the event trigger thing, then put the Player Animator block down put Jetstreamsamtest1 in the block saved it then went to workspace settings and added the plugin Player Animator waited for it to refactor workspace then saved the mod then got the error I have been getting this error ever since I have been trying to make this mod.) Please tell me what I did wrong.

**Comment by NerdyPuzzle** [comment]
You only need it after your mod is exported. either explain this more clearly or this issue is invalid.

**Comment by MetalMr** [comment]
But How do I use the Player Animator if when I open Minecraft it goes to the error page and I can't do anything else then look at the error.

**Comment by NerdyPuzzle** [comment]
If you have the mod in the mods folder in your workspace then delete it. It is decompiled with your workspace.

**Comment by NerdyPuzzle** [comment]
this is not an issue with the plugin, therefore this issue is closed. do not open another one.
